# Generated by Django 5.0.7 on 2024-08-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_closed_post_engagement_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='num_posts',
            field=models.IntegerField(default=0),
        ),
    ]
